### PR TITLE
Nullable regression

### PR DESCRIPTION
**Pull request by hpx7**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [x] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [ ] This PR is associated with an existing issue?

**Closing issues**

Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by hpx7** [comment]
@WoH before I go further with this, could you quickly take a look and confirm whether the test I added is indeed the desired behavior? The test is currently failing (but it used to work in 5.1.1), and I'd like to try and contribute a fix once I get your confirmation

**Comment by WoH** [comment]
Yeah. Nullable and x-nullable, but the prop should be required. That's correct

**Comment by WoH** [comment]
Thanks for taking a look into that

**Comment by WoH** [comment]
Can you take a look at the tests?

**Comment by hpx7** [comment]
@WoH I was able to track down that https://github.com/lukeautry/tsoa/pull/1498 was the change which broke this (the test passes on the commit prior), but I haven't been able to figure out the right way to fix it yet.

**Pull request closed without merging**
