### PR TITLE
Fixed a very stupid mistake that should've been caught by tests

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
Whoops...

(Sorry @dgreene1)

### CODE REVIEW

**Comment by WoH** [comment]
Is there a testing story for this?

**Comment by HoldYourWaffle** [comment]
Don't use a GUI program that doesn't run commit hooks.
Additionally, actually pay attention to if the tests have ran, instead of assuming they did "because there is a commit hook".

**Comment by WoH** [comment]
Ok, understood. The tests were not executed but would've caught the issue if they were.

**Comment by HoldYourWaffle** [comment]
Yup. It was literally just me not paying enough attention.

**Pull request merged**
