### PR TITLE
Upgrade handlebars dependency to ^4.5.3

### LINKED ISSUE #539: Upgrade handlebars version due to security vulnerabilities
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description
The current use of handlebars version 4.1.2 has various security issues. It would be great if tsoa could be upgraded to use a handlebars version above 4.5.3.

Let me know if you require any further information.

### PR DESCRIPTION
**Pull request by bvwells**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [ ] Have you written unit tests?
* [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
* [x] This PR is associated with an existing issue? 

**Closing issues**

closes #539

### If this is a new feature submission:

* [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

None that I can think of.

**Test plan**

No tests added.

### CODE REVIEW

**Comment by WoH** [comment]
Thanks for the PR! :+1:

**Comment by bvwells** [comment]
Thanks for the merge @WoH!

**Comment by bvwells** [comment]
@WoH, forgot to ask. Any ideas when the next patch release of tsoa will be?

**Comment by WoH** [comment]
Pinging @dgreene1.

**Comment by dgreene1** [comment]
@bvwells thank you for being a member of the tsoa community. I published this fix as part of `v2.5.10`. If you're enjoying using tsoa, we always appreciate when our users share the love on Twitter, Reddit, or [Dev.to](https://dev.to/).

**Comment by bvwells** [comment]
Thanks @dgreene1, great news! Thanks for all the help and great tool!

**Pull request merged**
