### PR TITLE
TypeScript 4.1 Compiler API, TemplateLiteralStrings, Key Remapping in Mapped Types

### PR DESCRIPTION
**Pull request by WoH**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [x] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Todo:**

- [x] Upgrade tsoa to be TS 4.1-dev compatible
- [x] Upgrade to TS 4.1.0 (blocked)
- [x] Upgrade ESLint / prettier to be TS 4.1 compatible
- [x] Simple referenced Template Literal Type
- [x] Inline TLTs
- [x] Mapped Type Remappings

### CODE REVIEW

**Comment by simllll** [comment]
I just stumpled upon a bug with template literal types, and found this. I guess it's not released yet, is there any pre release I can test?

**Comment by WoH** [comment]
> I just stumpled upon a bug with template literal types, and found this. I guess it's not released yet, is there any pre release I can test?

No

**Comment by simllll** [comment]
> > I just stumpled upon a bug with template literal types, and found this. I guess it's not released yet, is there any pre release I can test?
> 
> No

Anything I can do to help with the next release?

**Comment by WoH** [comment]
> Anything I can do to help with the next release?

Review #857

**Pull request merged**
