### PR TITLE
Support authentication and multi response

### PR DESCRIPTION
**Pull request by isman-usoh**
issues #20 #32 

### Authentication 
```json
{
  "swagger": {
    "securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "access_token",
            "in": "query"
        },
        "tsoa_auth": {
            "type": "oauth2",
            "authorizationUrl": "http://swagger.io/api/oauth/dialog",
            "flow": "implicit",
            "scopes": {
                "write:pets": "modify things",
                "read:pets": "read things"
            }
        }
    },
    ...
  },
  "routes": {
    "authenticationModule": "./authentication",
    ...
  }
}
```

`./authentication.ts`
```ts
import * as express from 'express';
export function expressAuthentication(request: express.Request, securityName: string, scopes?: string[]): Promise<any> {
    let token;
    if (request.query && request.query.access_token) {
        token = request.query.access_token;
    }

    if (token === 'abc123456') {
        return Promise.resolve({
            id: 1,
            name: 'Ironman'
        });
    } else {
        return Promise.reject({});
    }
};

import * as hapi from 'hapi';
export function hapiAuthentication(request: hapi.Request, securityName: string, scopes?: string[]): Promise<any> {
    ...
}

import { Request } from 'koa';
export function koaAuthentication(request: Request, securityName: string, scopes?: string[]): Promise<any> {
    ...
}
```
`./contollers/securityController.ts`
```ts
import { Get, Route, Security, DefaultResponse } from 'tsoa';

@Route('secure')
export class SecureController {
    @DefaultResponse<ErrorResponseModel>('Unexpected error')
    @Security('api_key')
    @Get("UserInfo")
    public async userInfo(@Request() request: any): Promise<UserResponseModel> {
        return Promise.resolve(request.user);
    }
}
```

### Response

`./controller.ts`
```ts
import { Get, Route, Security, Response } from 'tsoa';
import { ErrorResponseModel, UserResponseModel } from './models';

@Route('secure')
export class SecureController {
    @Response<ErrorResponseModel>('401', 'Unexpected error')
    @Security('api_key')
    @Get("UserInfo")
    public async userInfo(@Request() request: any): Promise<UserResponseModel> {
        return Promise.resolve(request.user);
    }
}
```
`./models.ts`
```ts
interface ErrorResponseModel {
    code: string;
    message: string;
}
interface UserResponseModel {
    id: number;
    name: string;
}
```

### CODE REVIEW

**Comment by lukeautry** [comment]
Nice, thanks for this. Will code review this weekend.

**Comment by lukeautry** [comment]
@isman-usoh This looks really good! I love what you did with the error response/default response stuff. That's been needed and the way you implemented it is exactly what I would expect it to look like.

I pushed up some changes just to fix up tests a bit and fix a few types/semantic code errors, but overall this is very good.

**Comment by lukeautry** [comment]
@isman-usoh This is live in 1.0.18.

**Comment by azaeng04** [comment]
@lukeautry @isman-usoh 
What if I want to display a custom error message? Cos this `@Response<ErrorResponseModel>('401', 'Unexpected error')` is just the description section of the model.

What if I have more than one error message that I want to return with different status codes?

Does tsoa cater for this?

Cos this is all I am seeing in the documentation: 

### **Specify error response types for Swagger**
```
@Response('400', 'Bad request')
@DefaultResponse<ErrorResponse>('Unexpected error')
@Get('Response')
public async getResponse(): Promise<TestModel> {
    return new ModelService().getModel();
}
```

**Pull request merged**
