### PR TITLE
manage generic array parameters

### PR DESCRIPTION
**Pull request by tguyard**
I was getting an error when trying to parse an interface with a generic array attribute. For example 
`
export interface MyInterface<T> {
  items: T[];
}
` couldn't be parsed (unable to find T)

With a very small modification I was able to manage this specific case.

### CODE REVIEW

**Comment by lukeautry** [comment]
@tguyard Looks good, can you fix the merge conflict on this one?

**Comment by tguyard** [comment]
It's done

**Comment by egandro** [comment]
Can we fix this? It's also on my todo list.

**Comment by dgreene1** [comment]
@WoH is there anything from this PR that can be salvaged? It’s pretty old. I’m going to close it since it most likely is too far diverged from master.

**Comment by dgreene1** [comment]
Note: for future readers, a response of SomeGeneric<T> Is fully supported as of 2.4.10

**Pull request closed without merging**
