### PR TITLE
Generate OpenAPI3 requestBody output for @BodyProps 

### PR DESCRIPTION
**Pull request by joppino**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [X] Have you written unit tests?
* [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
* [X] This PR is associated with an existing issue?

**Closing issues**

### If this is a new feature submission:

* [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by WoH** [comment]
Could you replicate [these tests](https://github.com/lukeautry/tsoa/blob/master/tests/integration/koa-server.spec.ts#L869) in the [openapi3-express server specs](https://github.com/lukeautry/tsoa/blob/master/tests/integration/openapi3-express.spec.ts)?

**Comment by joppino** [comment]
Sure. Been busy for a while but I hope I'll have some time during the week.

**Comment by joppino** [comment]
Hey there,

Finally I found some time to work on this. Just to be sure I'm not getting anything wrong. I've done the tests and tested that without the patch they don't work. But it has been something like a copypaste work.
I want to be sure that I've understood your request correctly - it seems too easy.

  OpenAPI3 Express Server
    ✓ should valid model validate
    ✓ should invalid model validate
    ✓ parses body props parameters
    ✓ can get request with generic type
    ✓ can get request with generic array
    ✓ can get request with generic primitive type
    ✓ can get request with generic primitive array
    ✓ can post request with a generic body

Thanks

**Comment by WoH** [comment]
> I want to be sure that I've understood your request correctly - it seems too easy.

Glad to hear :laughing: 
Yes it shouldn't have been too hard, but especially this one: 
`✓ parses body props parameters`
is supposed to prevents regressions in the future.

**Comment by WoH** [comment]
Can you push these tests?

**Comment by joppino** [comment]
I was trying to update the pull  request, but have now several merge conflicts and also build problems on the current master. Is it me?

**Comment by WoH** [comment]
Yes, master points at the branch for now, and a lot of things have changed between the 2.x and the 3.x (now master) branches.
This is why I changed the target for this PR to 2.x to avoid merge conflicts.
If you push the tests, we can merge this into 2.x and I'll rebase for master.

**Comment by joppino** [comment]
I'm receiving this at pre-commit (this is not one of the files in my PR)

src/cli.ts:71:18 - error TS2430: Interface 'ExtendedSpecConfig' incorrectly extends interface 'SpecConfig'.
  Types of property 'noImplicitAdditionalProperties' are incompatible.
    Type '"silently-remove-extras" | "throw-on-extras" | "ignore"' is not assignable to type 'boolean | "silently-remove-extras" | "throw-on-extras" | undefined'.
      Type '"ignore"' is not assignable to type 'boolean | "silently-remove-extras" | "throw-on-extras" | undefined'.

71 export interface ExtendedSpecConfig extends SpecConfig {

**Comment by WoH** [comment]
that error messge leads me to believe you are still or were on master/3.x. Please make sure there are no caching issues, `ExtendedSpecConfig` should not be anywhere in the 2.x code.

**Comment by TedChenNZ** [comment]
Hi, I was wondering if there was anything I could do to get this PR (or something similar) merged?

**Pull request closed without merging**
