### PR TITLE
Fix incompatibility with latest InversifyJS 

### LINKED ISSUE #1717: Incompatibility with recent versions of inversifyJS
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

If you define container configuration according to current docs

```ts ioc.ts
# Previously if you have, for example:  
decorate(injectable(), Controller);

ioc.bind<IServer>(Types.IServer).to(Server);
ioc.load(buildProviderModule());
export { ioc };
and point to it in the tsoa.json as iocModule,
```
Container expected to be compiled

## Current Behavior
If you define container configuration according to current docs

```ts ioc.ts
# Previously if you have, for example:  
decorate(injectable(), Controller);

ioc.bind<IServer>(Types.IServer).to(Server);
ioc.load(buildProviderModule());
export { ioc };
```

and point to it in the tsoa.json as iocModule

And during build we getting error
```ts
tsoa-generated/routes.ts:622:23 - error TS2322: Type 'Container | IocContainer' is not assignable to type 'IocContainer'.
  Type 'Container' is not assignable to type 'IocContainer'.
    Types of property 'get' are incompatible.
      Type '<T>(serviceIdentifier: ServiceIdentifier<T>) => T' is not assignable to type '{ <T>(controller: { prototype: T; }): T; <T>(controller: { prototype: T; }): Promise<T>; }'.
        Types of parameters 'serviceIdentifier' and 'controller' are incompatible.
          Type '{ prototype: any; }' is not assignable to type 'ServiceIdentifier<any>'.
            Type '{ prototype: any; }' is missing the following properties from type 'Function': apply, call, bind, length, and 4 more.
                 const container: IocContainer = typeof ioc === 'function' ? (ioc as IocContainerFactory)(request) : ioc;
``` 

## Possible Solution

This happens due to recent changes in the InversifyJS

Signature of  `export type ServiceIdentifier<T = unknown> = (string | symbol | Newable<T> | Abstract<T>);`
has been changed to

https://github.com/inversify/InversifyJS/blob/master/src/interfaces/interfaces.ts#L66

that borrowed from here:

https://github.com/inversify/monorepo/blob/main/packages/container/libraries/common/src/services/models/ServiceIdentifier.ts#L3C8-L8C14 

The simplest solution without doing changes to libraries itself to make wrapper, in TSyringe way:

```ts ioc.ts
# Previously if you have, for example:  
decorate(injectable(), Controller);

ioc.bind<IServer>(Types.IServer).to(Server);
ioc.load(buildProviderModule());
export { ioc };
and point to it in the tsoa.json as iocModule,
```
Now you need to wrap it up:
```ts container.ts
import { IocContainer } from '@tsoa/runtime';
import { ioc } from './ioc';

export const iocContainer: IocContainer = {
   get: <T>(controller: { prototype: T }): T => {
      return ioc.resolve<T>(controller as never);
   },
};
```
And point to it in tsoa.json 

Another way to fix behavior is to update signature of container definition here
https://github.com/lukeautry/tsoa/blob/master/packages/runtime/src/interfaces/iocModule.ts#L2

  
## Context (Environment)

Version of the library: 6.5.0
Version of NodeJS: 22.11

- Confirm you were using yarn not npm: [ ]

### PR DESCRIPTION
**Pull request by helios-ag**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Closes #1717

### CODE REVIEW

**Comment by helios-ag** [comment]
@WoH @jackey8616 bump

**Comment by amt8u** [comment]
@dgreene1 @lukeautry bump. The PR is open for sometime now.

**Comment by helios-ag** [comment]
A bit weird, that GHA fails...

**Comment by helios-ag** [comment]
@WoH bump

**Review by WoH — APPROVED** [review]
I'll take a look at who broke types upstream & why separately. LGTM

**Comment by helios-ag** [comment]
@WoH bump

**Comment by WoH** [comment]
I'll fix Base over the weekend and promise to get this over the finish line.
Sorry for the delays, I had personal stuff taking priority.

**Comment by helios-ag** [comment]
Thanks @WoH

**Pull request merged**
