### PR TITLE
Generates a json schema to improve developer experience

### PR DESCRIPTION
**Pull request by arthurfiorette**
This is a pretty simple pull request that auto generates a schema.json to include autocompletions to tsoa json configuration file.

I think you should also include the `$schema` property in every documentation example. (But that lives under another repo)

```json
{
  "$schema": "./node_modules/tsoa/schema.json",
  ...
}
```

Example:

image

### CODE REVIEW

**Comment by WoH** [comment]
Love the idea, but shouldn't we treat the produced JSON as a build artifact and ignore it in git?

**Comment by arthurfiorette** [comment]
I don't think so, this way people can link to specific versions using raw.githubusercontent

**Comment by tsimbalar** [comment]
Maybe it should be hosted with the documentation ? 

https://tsoa-community.github.io/docs/

**Comment by arthurfiorette** [comment]
That's also another good option. Turborepo does it.

https://turborepo.org/schema.json

But that's probably because their documentation lives under the same repo as the source.

**Comment by WoH** [comment]
We can link into specific files on npm via socket.dev's file explorer.

https://socket.dev/npm/package/@tsoa/runtime/files/4.1.0/dist/config.d.ts

**Comment by arthurfiorette** [comment]
Did you guys decie what option should be done?

**Comment by tsimbalar** [comment]
I was going to suggest maybe adding it to https://www.schemastore.org , because most IDEs just know how to point to it ... but it turns out it's there already !!

see https://json.schemastore.org/tsoa.json or https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsoa.json 

Maybe it just needs to be updated there ?

**Pull request closed without merging**
