### PR TITLE
Don't overwrite status codes from SuccessResponse if the controller's…

### PR DESCRIPTION
**Pull request by brian-pinwheel**
… status is undefined

This is to address Issue #938 

### All Submissions:

- [ X] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [ X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [ X ] This PR is associated with an existing issue?

**Closing issues**

Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

None

### CODE REVIEW

**Comment by WoH** [comment]
@devnev I think this makes sense, and it doesn't conflict with your interpretation of what should happen in these cases,  right?

**Comment by devnev** [comment]
@WoH Yeah I think this makes sense too.

**Comment by WoH** [comment]
@brian-pinwheel LGTM then, but could you add a test for this?

**Comment by brian-pinwheel** [comment]
> @brian-pinwheel LGTM then, but could you add a test for this?

@WoH I would love to, but honestly, this is my first time using Express and don't know how to write tests.  I come from more of a Java world, which is why TSOA was a natural fit.  Unfortunately, I have other higher priorities at this time that prevent me from taking the time to learn how the tests work. I have to imagine the test wouldn't take very long, but the time taken to debug the issue has set the project back so trying to catch back up to our release date.

**Comment by WoH** [comment]
I added a test on master. Please note that using `@SuccessResponse` on controllers that inherit `Controller` by tsoa will still lead to unforseen consequences if you're using Singleton controllers.
Repro: Handler `handleA` uses `setStatus` to set the status prop (not no longer `undefined`, but now, for example 404. ). Now we call `handlerB`, which uses `@SuccessResponse(418)`. At runtime, the controller is still the singleton created by your Factory/DI with a status prop of 404. The check determines the code should be 404 || 418 -> 404 is returned).

Solutions: 
a) Don't use singleton contollers
b) reset the status code to undefined

**Comment by devnev** [comment]
FYI, we're now avoiding any accidental false sharing by enabling `useSuccessResponseCode` and not inheriting `Controller`, which bypasses the code in the `isController(...)` condition and thus the use of controller state. For the main response from a method, the status comes from `@SuccessResponse`, and when we need an alternative response status, we use an `@Res` callback.

**Comment by WoH** [comment]
Exactly. And the `@SuccessStatus` + `@Res` is the better API that we should encourage. This PR allows for the admittedly dubious `this.setStatus(undefined as number)` escape that you can use to migrate.

**Pull request merged**
