### PR TITLE
Feat: Support multiple @example at method comment

### LINKED ISSUE #650: Support multiple examples
It looks like open api 3 supports multiple examples.  It would be great to support this.

https://swagger.io/docs/specification/adding-examples/

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
"Location": {
    "examples": [
      {
        "code": "98104",
        "country": "US",
        "province": "WA",
        "locality": "Seattle"
      },
      {
         "code": "BR12AA",
         "country": "GB",
         "province": "London"
      },
      {
          "country": "NL"
      }
    ]
}
```

```ts
/**
 * @example {
 *   "code": "98104",
 *   "country": "US",
 *   "province": "WA",
 *   "locality": "Seattle"
 * }
 *
 * @example {
 *   "code": "BR12AA",
 *   "country": "GB",
 *   "province": "London"
 * }
 *
 * @example {
 *   "country": "NL"
 * }
 */
export interface Location {
```

## Current Behavior
Currently only one example shows up

## Context (Environment)
Version of the library: 3.0.4
Version of NodeJS: 12.12.0
* Confirm you were using yarn not npm: [x]

## Detailed Description
If multiple example decorators are found, render an examples array in the swagger document instead of example.

## Breaking change?
No

### PR DESCRIPTION
**Pull request by jackey8616**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**
Closes #650 

### If this is a new feature submission:

- [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

This PR contains several change at below:
- Fixes the example generating at OpenAPI2 which is not a valid format.
- Add multiple examples support in methods.
- Add GenerateMetadataError throws while user provides a wrong JSON-format example.
- Specifically defined the type of example which is Example in OA2, Example3 in OA3.

Seeking more detail usage, please reference the `exampleController` in `tests/fixtures/controllers/exampleController.ts` file.

### CODE REVIEW

**Comment by WoH** [comment]
Can you add tests for this?
OpenAPI 2: https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/definitionsGeneration/definitions.spec.ts
OpenAPI 3: https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/schemaDetails3.spec.ts

**Comment by jackey8616** [comment]
@WoH 
I've added some cases into unit test to test the result  after generating single or multiple examples.  

But here is a test case that I have no idea where to put: An error would throw when user provides an incorrect JSON-format example in jsDoc.  
Do you have any suggestion?

**Comment by WoH** [comment]
> Do you have any suggestion?

Sure, 'tests/unit/swagger/pathGeneration/' would be a good fit.
You can add a exampleRoutes.spec.ts and do something like what we already do for the GetController in getRoutes.spec.ts

**Comment by jackey8616** [comment]
I completed the test case earlier.  
And I put it in `tests/unit/swagger/schemaDetails.spec.ts` both version 2 and 3.  
Also make a negative cases to check incorrect JSON-format.  

I think this PR is ready for review and merge.  
Thank you.

**Comment by WoH** [comment]
Ah, didnt't get a chance to check that yet, my bad.
I'll try to find time to take a look tomorrow, but it looks great so far!
Thanks a lot

**Comment by WoH** [comment]
LGTM

**Pull request merged**
