### PR TITLE
Hashmap support

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Support
```
export interface TestSubModelContainer {
  [key: string]: TestSubModel2;
}
```

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@lukeautry I'll update this PR shortly to match new master

**Comment by alexey-pelykh** [comment]
@lukeautry done, please review

**Comment by alexey-pelykh** [comment]
@lukeautry any update on this?

**Comment by lukeautry** [comment]
Merged. Thanks @alexey-pelykh!

**Pull request closed without merging**
