### PR TITLE
Handle Record<string, never> type

### LINKED ISSUE #1535: 6.0.0 regression: GenerateMetadataError: Unknown type: NeverKeyword
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

In 5.1.1, tsoa was able to handle the following type (which represents an empty object, i.e. `{}`)

```ts
Record<string, never>
```

## Current Behavior

This breaks starting in 6.0.0-rc.0

```
There was a problem resolving type of 'Record<string, never>'.

Generate routes error.
 GenerateMetadataError: Unknown type: NeverKeyword
At unknown position...
This was caused by '<unknown name>'
    at TypeResolver.resolve (/project/node_modules/@tsoa/cli/src/metadataGeneration/typeResolver.ts:470:13)
    at <anonymous> (/project/node_modules/@tsoa/cli/src/metadataGeneration/typeResolver.ts:244:113)
```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 6.0.0
Version of NodeJS: 18.17.1

- Confirm you were using yarn not npm: [ ]

## Breaking change?

This is a breaking change in tsoa version 6

### PR DESCRIPTION
**Pull request by hpx7**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Closes #1535 

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by hpx7** [comment]
@WoH does this look ok to merge?

**Comment by WoH** [comment]
Can you add a test please? Add it to the test model and make sure the spec is fine.

**Comment by hpx7** [comment]
> Can you add a test please? Add it to the test model and make sure the spec is fine.

I have added a test, please take a look and let me know if you'd like me to add any more.

The macos-latest build failure seems to be a flake.

**Comment by WoH** [comment]
LGTM!

**Comment by WoH** [comment]
You could check for additonalProperties which should, regardless of the runtime validation strictness should be false here.
But this is a clear improvement, so I'm happy to merge it as is. Thanks for opening a PR!

**Pull request merged**
