### PR TITLE
[#218] Bubble up validation errors to the global Koa error handler.

### PR DESCRIPTION
**Pull request by aidenwallis**

### CODE REVIEW

**Comment by endor** [comment]
Anybody who uses koa any opinions on this? @yolofy @cjam

**Comment by cjam** [comment]
@endor it seems reasonable to me.  I wonder if you may want to put a throw into the authentication checks as well?  see ⬇️ 

https://github.com/lukeautry/tsoa/pull/276/files#diff-f2b44027f6bd1ac07d07eac3a27d7507R92

**Comment by endor** [comment]
@aidenwallis do you still want to extend this with @cjam's suggestion?

**Comment by aidenwallis** [comment]
Awesome, thank you!

**Comment by x1yy** [comment]
this `context.throw(..` at `registerRoutes` makes validation fields error response fail.

this is the response
before:
```
{
	"fields": {
		"proposal.password": {
			"message": "'password' is required"
		}
	},
	"message": "",
	"status": 400,
	"name": "ValidateError"
}
```
after:
```
Anerroroccurredduringtherequest
```

**Comment by cjam** [comment]
Hmm. It almost seems that the error isn't being exposed, which might happen if `error.status` [here](https://github.com/aidenwallis/tsoa/blob/59d200e9c721a8a6d9cc799b64d5d2a9b26eb969/src/routeGeneration/templates/koa.ts#L55) is undefined as it would default the value to `500` in `ctx.throw` (based on https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxthrowstatus-msg-properties).  I've had issues with extending the error object in the past in typescript for some reason.  Are you able to debug and inspect the error object in the `catch` at `registerRoutes` and confirm the status being passed into `ctx.throw`?

**Pull request merged**
