### PR TITLE
feat: Add optional x-enum-varnames support

### LINKED ISSUE #752: x-enum-varnames support
OpenAPI Generator allows with the vendor extension [x-enum-varnames](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/templating.md#extensions) to name enum values. At least for numeric enums it would be very helpful to support this extension.

https://github.com/lukeautry/tsoa/pull/700 does not seem to help in this case.

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
enum CorePermissionEnum {
    test = 0
}
```

should lead to

```json
"CorePermissionEnum": {
  "enum": [0],
  "x-enum-varnames": ["test"],
  "type": "number"
}
```

## Current Behavior

```ts
"CorePermissionEnum": {
  "enum": [0],
  "type": "number"
}
```

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 14.5.0

## Breaking change?

As it is not part of the standard but somewhat important for usable numeric enums it should probably be disabled by default and enabled through the spec-configuration.

### PR DESCRIPTION
**Pull request by ml1nk**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

closes #752

### If this is a new feature submission:

- [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by WoH** [comment]
Would you mind adding tests for the spec generators?

**Comment by ml1nk** [comment]
> Would you mind adding tests for the spec generators?

Sorry for the delay. I couldn't find configuration variation testing in v2, so i only added a variant to v3. Ist it enough?

**Comment by WoH** [comment]
I think an entire run of all oas3 spec tests may be a bit of an overkill. I think we can just generate the oas3 and run only a fews tests  with it. I'd approach oas2 similarly, the tests are here: https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/definitionsGeneration/definitions.spec.ts

**Comment by ml1nk** [comment]
I reverted the commit and added the same tests for oas2 and oas3 without a full run.

**Comment by WoH** [comment]
Thanks you very much!

**Pull request merged**
