### PR TITLE
Add support for file uploads

### PR DESCRIPTION
**Pull request by ezra-quemuel**
- Adds support for the @UploadedFile and @UploadedFiles decorators
- Adds file upload support for Express and Koa using multer, and uses a custom middleware for Hapi
- Exposes a File interface for an uploaded file

- Fixes https://github.com/lukeautry/tsoa/issues/93

### CODE REVIEW

**Comment by lukeautry** [comment]
Thanks @ezra-quemuel! Looks pretty good; is there a way to upload the file to something other than the disk though?

**Comment by ezra-quemuel** [comment]
Not currently. The problem with adding that kind of extended functionality is that currently the Hapi middleware is custom. So any features like uploading a file to memory would have to be manually added to the custom Hapi middleware (which in that case, it should probably be its own library). I'd be fine with adding the support for Express and Koa, but if I do, I'd say that Hapi specifically would not be supported. Thoughts?

**Comment by ezra-quemuel** [comment]
As a note, Hapi currently doesn't have a standard library for file upload support AFAIK. I'm open to switching the implementation if there are better solutions.

**Comment by ezra-quemuel** [comment]
I've noticed a few issues related to swagger generation, so we should hold off on the merging of this PR. I'll have to add a FormData decorator to add support for extra form fields during file uploads (swagger doesn't allow body parameters with a multipart/form-data request, which makes sense).

**Comment by ezra-quemuel** [comment]
@lukeautry Updated.

- Added support for the FormField decorator
- Added validation to prevent Body and BodyProps to be used with any formData (swagger doesn't allow this)
- Updated docs

**Comment by ezra-quemuel** [comment]
@lukeautry fixed merge conflicts

**Comment by devanshah1** [comment]
@lukeautry Can we get this merged into master, and have a release pushed out. Thanks.

**Comment by egandro** [comment]
This one is also on my ToDo list. I'd like to have multer as middleware for express.

**Comment by egandro** [comment]
@ezra-quemuel  is it ok with you that I take parts of your code and add a middleware like we have it in the authentication layer?

I'd love to have multer for this for express.js (https://github.com/expressjs/multer) we just need some custom function called that takes the request/response

**Comment by nartc** [comment]
@egandro I’ve forked and added Multer support to the project. I never submitted a PR though because it is based off of this PR and I feel like it’s not really scalable. All it does was to add multer so that request.file returns the file selected, also added to the swaggerGenerator type: file and consumes: multipart/form-data

**Comment by nartc** [comment]
I install the package on my personal project using my forked-repo so I do have the feature

**Comment by egandro** [comment]
@nartc Ok cool! I'll reintegrate it to this project. 

I might create some driver structure as it is not 100% compatible with all supported web middlewares.

Also the multer feature needs by itself to be very flexible (file, ram or there is even multer s3)

I really love the swagger feature, because I've written code generators for android and angular ng clients on top of that!

**Comment by nartc** [comment]
@egandro Me too. I'm currently using TSOA in a MEAN Stack application. I've tried the `personally-added` multer middleware last night and `swagger-codegen` generates method that takes in `Blob` for `type: file` in Swagger spec file. The backend receives the file and everything's fine. I'll hook it up to a S3 storage to see how it goes.

**Comment by AmazingTurtle** [comment]
Until then I have added a short description on how to do this with multer "manually" (not that much effort though).

https://github.com/lukeautry/tsoa/pull/198/files

**Comment by nartc** [comment]
@egandro just wanna update that I was able to upload file to Google Cloud Storage using multer in tsoa template.

**Comment by gabibianconi** [comment]
Hello, I would like to use TSOA in my project but I have to develop APIs with Files as parameters. When is this PR going to be merged into master?

**Comment by AmazingTurtle** [comment]
@gabibianconi did you take a look at https://github.com/lukeautry/tsoa/pull/96#issuecomment-366465691 ?

**Comment by gabibianconi** [comment]
No, I didn't. I will take a look. Thanks!

**Comment by jamestharpe** [comment]
Bump. The workaround... works, but having this feature be a part of TSOA would be even better!

**Comment by AmazingTurtle** [comment]
This commit lasts for 1 year and I don't see someone would actually resolve merge conflicts... I'd take a look at this one myself when I have time.

**Comment by dgreene1** [comment]
With this PR being two years old, it’s best to close it for housekeeping purposes. If someone wants to bring it back to life, they can. I just took on tsoa as one of the maintainers so I’m happy to look at PRs. In the meantime, the readme documents a good workaround: https://github.com/lukeautry/tsoa#upload-files

**Pull request closed without merging**
