### PR TITLE
Upgrade koa-router to @koa/router, fix type errors

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Some additional `@types` packages needed to be updated.
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [ ] ~Have you written unit tests?~
* [ ] ~Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?~
* [x] This PR is associated with an existing issue?

**Closing issues**
closes https://github.com/lukeautry/tsoa/issues/644

### CODE REVIEW

**Comment by WoH** [comment]
LGTM, thanks for your contribution!
Would you mind filing this PR agains the 3.x branch aswell?

**Comment by michaelbeaumont** [comment]
As far as `koa-router` is concerned there weren't any breaking changes, just the name update. For `@types/koa` just some new parameters were added.
I.e. I don't think so.

**Comment by michaelbeaumont** [comment]
@WoH  can this be merged?

**Comment by WoH** [comment]
Yes. It'll be included in the next release. Thank you very much for your contribution.

**Pull request merged**
