### PR TITLE
Add support for injected express request and other values

### PR DESCRIPTION
**Pull request by andreasrueedlinger**
Here is a proposition how to implement support for express request parameter in controllers as well as other custom values injected by a custom template.
See also my proposition/question [here](https://github.com/lukeautry/tsoa/issues/7)

### CODE REVIEW

**Comment by lukeautry** [comment]
@andreasrueedlinger Thanks for this change, I will review some time in the next 24 hours.

**Comment by lukeautry** [comment]
@andreasrueedlinger Sorry, took longer to get to this than I thought.

Two things:

1) Would you mind adding a quick section to the readme with usage for Request/Inject?
2) Let's expose the new decorators in https://github.com/lukeautry/tsoa/blob/master/src/index.ts

Thanks!

**Comment by andreasrueedlinger** [comment]
Thanks for the feedback. I added your 2 suggestions.

**Comment by lukeautry** [comment]
@andreasrueedlinger Thanks; this is live in 1.0.3.

**Comment by danzel** [comment]
Awesome!
I'm not quite sure how to use the `@Inject` property however, do I need to edit this template:
https://github.com/lukeautry/tsoa/blob/master/src/routeGeneration/templates/express.ts
to do the injecting?

**Comment by andreasrueedlinger** [comment]
@danzel If you want to use `@Inject` you need to write your own template (using the one you referenced as base).
Then you can perform your injection in this section:
```ts
      function getValidatedParams(params: any, request: any, bodyParamName?: string): any[] {
        const requestParams = getRequestParams(request, bodyParamName);

        return Object.keys(params).map(key => {
            if (params[key].injected === 'inject') {
              if (key === 'nameOfYourInjectedParameter') {
                return 'yourValueOrObjectHere';
              }
              return undefined;
            } else if (params[key].injected === 'request') {
              return request;
            } else {
              return ValidateParam(params[key], requestParams[key], models, key);
            }
        });
```

What is your use-case of parameter injection? Normally you should be fine to use normal dependency injection with inversify or similar. In my case I adapted the express template as follows:
```ts
// import the inversify kernel (this is unfortunately custom code, otherwise we could add an inversify-js template)
import { kernel } from './ioc/ioc';

export function RegisterRoutes(app: any) {
  // ...

  // instead of `const controller = new {{../name}}();`
  const controller = kernel.get<{{../name}}>({{../name}});
  // ...
}

**Comment by danzel** [comment]
Awesome thanks, yeah that is what I was trying to achieve :)

**Pull request merged**
