### PR TITLE
Allowing enums with an empty string literal to be correctly generated in swagger

### LINKED ISSUE #522: Empty string among union values causes union to be resolved as 'any' instead of 'string'
Unions `type YesNo = "Yes" | "No" | ""` will have swagger generated with type object, as typeResolver produces 'any' data type.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Generates a swagger type enum and all its values

## Current Behavior
Generates a swagger type object

## Steps to Reproduce
Generate swagger for `type YesNo = "Yes" | "No" | ""`

## Context (Environment)
Version of the library: 2.5.7
Version of NodeJS: 8
* Confirm you were using yarn not npm: [ ]

## Breaking change?
Potentially, as people may rely on empty strings to not produce correct swagger enum. Having empty strings in enums is very rare though.

### PR DESCRIPTION
**Pull request by rgripper**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [x] Have you written unit tests?
* [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
* [x] This PR is associated with an existing issue?

**Closing issues**
closes #522

### CODE REVIEW

**Comment by dgreene1** [comment]
@rgripper your tests are failing. Please click on the red :x: above to see what’s wrong.

**Comment by WoH** [comment]
@dgreene1 that's a ci issue: `- Workflows can't be executed on this repository. Please check your payment method or billing status.`

@rgripper I don't think the linter should permit `== null` even though this is technically correct, however confusing since the `==` has some unintuitive behavior considering JS default coercion.

**Comment by dgreene1** [comment]
@lukeautry / @WoH / @gripper I really don’t have time to look into the CI issues. I’m sorry to disappoint. Work is insane right now.

**Comment by rgripper** [comment]
@dgreene1 Looks like Actions are generally available now and this account type is not suppose to have them. https://github.com/ansible/community/issues/505
@WoH I checked what convention this code used and it was == for null/undefined. Linter can enforce this rule.

**Pull request merged**
