### PR TITLE
fix: add @types/multer as a peerdependency

### LINKED ISSUE #1251: Add @types/multer as peerDependency
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The `yarn build` CircleCI test should pass.

## Current Behavior

Screen Shot 2022-05-10 at 4 15 23 PM

## Possible Solution

I'm not aware of any solutions, so either a bug fix for this issue or a workaround would be appreciated.

## Steps to Reproduce

1. A Snyk scan has identified that tsoa@3.14.1 had vulnerable dependencies. 
2. I created a PR to upgrade to tsoa@4.0.0, which is then ran through a number of CircleCI tests. 
3. The last test `yarn build` fails due to the following error: `node_modules/@tsoa/runtime/dist/config.d.ts:43:18 - error TS2709: Cannot use namespace 'MulterOpts' as a type.`
4. The PR cannot be approved and merged.

## Context (Environment)

Version of the library: 4.0.0
Version of NodeJS: 16.14.2

- Confirm you were using yarn not npm: [x]

## Detailed Description
A fix for error TS2709.

## Breaking change?
No

### PR DESCRIPTION
**Pull request by dxphilo**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Put `closes #1251` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by dxphilo** [comment]
closes #1251

**Comment by WoH** [comment]
Can you please move this to the runtime package where it's actually being required?
On second glance, I think we can reasonably just add it as a regular dependency.

**Comment by dxphilo** [comment]
> Can you please move this to the runtime package where it's actually being required? On second glance, I think we can reasonably just add it as a regular dependency.

Sounds very reasonably to add it a dependency.

**Comment by marvasDE** [comment]
I have the same issue in my project. So I would like to see a merge of this PR.

**Pull request closed without merging**
