### PR TITLE
fix: throw an error when there are no controllers found

### PR DESCRIPTION
**Pull request by simllll**
With the ts4.8 issue it turns out tsoa does not throw any kind of error if there are zero controllers found. Which makes it even a bit hard to find the issue in first place. To prevent this in the future I added a check that throws an Error if there are no controllers discovered.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [x] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [ ] This PR is associated with an existing issue?

**Closing issues**

Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

potentially helps e.g. for #1301

### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

In my opinion it doesn't make sense to use tsoa without any controllers, but maybe I'm missing some special use cases?

**Test plan**

the added test catches the expected error when there are no controllers

### CODE REVIEW

**Comment by WoH** [comment]
https://github.com/TypeStrong/ts-node/issues/1839

**Comment by simllll** [comment]
quite some dependency updates needed to get this running again.
* dropped node 12 from test matrix (as it does not work with node 12 anymore)
* upgraded all deps (except chalk because it's esm only in version 5) to latest

should we maybe move that to a seperat PR?

**Comment by WoH** [comment]
Don't think this is only related to win (I hope)
https://github.com/lukeautry/tsoa/blob/master/packages/cli/src/metadataGeneration/metadataGenerator.ts#L41

**Comment by simllll** [comment]
It seems though it's only related to windows, it finishes successfully on linux and mac on the github actions (locally also on linux, tests are running fine).

**Comment by simllll** [comment]
Still fails on windows somehow with superagent.
```
tsoa-tests: err Error: read ECONNRESET
tsoa-tests:     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
tsoa-tests:   errno: -4077,
tsoa-tests:   code: 'ECONNRESET',
tsoa-tests:   syscall: 'read',
tsoa-tests:   response: undefined
tsoa-tests: }
```

first was thinking this could be related https://github.com/visionmedia/supertest/issues/617 but there is actually no http2.. kinda hard to figure it out on a non-windows env...

**Pull request merged**
