### PR TITLE
DevSupport: Coverage report & coveralls.io

### LINKED ISSUE #836: DevSupport: Want a code coverage for complete test
Since tsoa is using mocha as testing tool,  
I think we can introduce some coverage tools such as `nyc` or `istanbul` to help we contributors more efficiently on testing.  
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
A coverage tool which can generate reports and well-serve on internet like `coveralls.io` or anything coverage report serving service.  

## Current Behavior
Thanks for every collaborator, they use there eyes to helping us with test case coverage!

### PR DESCRIPTION
**Pull request by jackey8616**
Collaborators need to setup coveralls.io's repo toggle.  

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Closes #836 

### If this is a new feature submission:

- [x] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

### CODE REVIEW

**Comment by jackey8616** [comment]
@WoH This PR is done, please review.  
Thank you.

**Comment by WoH** [comment]
I checked this out earlier, but was confused as to why the reported coverage would be 0 for the runtime. Does not seem very realistic.

**Comment by jackey8616** [comment]
@WoH I studied a little bit.
And I think the runtime statement coverage with 0% is correct.

Controller's defined in tests/fixture was static analysis by tsoa/cli, which let coverage can be detect by nyc.
But since our integration testing code in tests/prepare.ts is also static analysis, server.ts inside each support platform like express or koa is actually not been bootstrap by nyc, that's why the coverage of runtime is always 0%.

If we want to coverage of runtime, I think we should comes out with another new way to bootstrap integration codes.  
IMHO, runtime code's 0% coverage is currently acceptable, since most of codes are just interface or type defined, only few files like `runtime/src/utils/assertNerver.ts`, `runtime/src/routeGeneration/templateHelper.ts` need to handle coverage.

**Comment by WoH** [comment]
Can you try to suggest a way to get proper reporting w/ regards to runtime coverage. I would disagree with the notion that "runtime code's 0% coverage is currently acceptable", this seems like one of the most important things tsoa should provide some sort of coverage information about.

**Comment by jackey8616** [comment]
@WoH 
Currently I have no idea how to let `runtime` package generate correspond coverage report.  
Since tsoa's test case is not directly access those decorators through typescript, thus nyc can not recognize them.  

For tsoa, most of codes inside `runtime` package are just sort of syntax sugar for bypassing typescript.  
Tsoa have its own analyzer to parsing them with typescript way.

**Comment by WoH** [comment]
My main issue is that the integration tests definitely run the templateHelpers, but the coverage does not reflect that:

```
----------------------------------|---------|----------|---------|---------|------------------------
File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s      
----------------------------------|---------|----------|---------|---------|------------------------
runtime/src/routeGeneration       |       0 |        0 |       0 |       0 |                        
  templateHelpers.ts              |       0 |        0 |       0 |       0 | 9-769                  
```

**Pull request closed without merging**
