### PR TITLE
Base, Controller and Method paths normalisation

### PR DESCRIPTION
**Pull request by amozh**
Fix for bug described in this issue https://github.com/lukeautry/tsoa/issues/155

### CODE REVIEW

**Comment by ajmath** [comment]
I think this PR broke folks who are using the root path.

For example, if I have left basePath off or set it to `/`, it will generate paths in my routes file like: `path: '//auth/okta/validate',` which will cause the http server (hapi in my case) to fail to launch.

The major difference in my case with this change is that basePath changes from `''` to `'/'` which causes the initial double slash.

After looking at the code, I'm not sure where there are so many parameters to the new function.  The second two are never used outside of the tests.

**Comment by amozh** [comment]
@ajmath Yeah, my bad. Missed this check:
src/cli.ts:83
```
config.basePath = config.basePath || '/';
```
Will fix it asap.

**Comment by amozh** [comment]
@ajmath here is the PR with fix
https://github.com/lukeautry/tsoa/pull/173

**Comment by ajmath** [comment]
Thanks.

**Pull request merged**
