### PR TITLE
#528: fix for the v3 securityshemes

### LINKED ISSUE #528: securitySchemes with open api
## Sorting

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Overview
specyfing the securitySchema in tsoa.json does not produce the correct open api definition in the yaml file.

e.g. 
```json
"securityDefinitions": {
			"TEST": {
				"type": "oauth2",
				"flow": "application",
				"tokenUrl": "/ats-api/auth/token",
				"scopes": []
			}
		},
```

produces:
```yaml
securitySchemes:
        TEST:
            type: oauth2
            flow: application
            tokenUrl: /ats-api/auth/token
            scopes: []
```

but should generate:
```yaml
securitySchemes:
       TEST:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: /ats-api/auth/token
            scopes: []
```

see also https://swagger.io/docs/specification/authentication/oauth2/
besides that the wording/flow differences between v2/v3 need either to be documented or considered for next major release to be changed. e.g:
* flow accessCode -> authorizationCode – Authorization Code flow (previously called accessCode in OpenAPI 2.0)
* flow application -> clientCredentials – Client Credentials flow (previously called application in OpenAPI 2.0)

## Expected Behavior
tsoa should generate valid yaml files out of the defined securityDefinition also for v3 / open api.

## Possible Solution
Abstact the security definition so that it can be used for v2 and v3 in a general way.

## Steps to Reproduce
1. create tsoa file with security definition flow application
2. generate open api doc
3. validate security schema

## Context (Environment)
Version of the library: 2.5.8
Version of NodeJS: v12.13.0

### PR DESCRIPTION
**Pull request by bajzat**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [x] Have you written unit tests?
* [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
* [x] This PR is associated with an existing issue?

**Closing issues**
closes #528 

**Test plan**

All possible Oauth2 flow added as configuration in unit tests.

### CODE REVIEW

**Comment by dgreene1** [comment]
@bajzat this PR looks good technically. The only reason I'm not merging this is because I don't know enough about the various OAuth flow data structures to confirm that this PR is correct. Do you know anyone else that you can have review this PR and give it a thumbs up? I'd just like to have one other person who isn't me review this.

**Comment by bajzat** [comment]
thanks, unfortunately, I don't have anyone who can review it from oauth2 perspective. I made the implementation based on which was sent by @simllll . https://swagger.io/docs/specification/authentication/oauth2/

**Comment by dgreene1** [comment]
K if @simllll approved it I will merge it.

**Comment by simllll** [comment]
I will look into it on the weekend! Thanks for the PR!

**Comment by simllll** [comment]
Hi all,
I just looked over it and tested my own use cases with it: looks great! All output is valid, even the cases without any defined scopes. (Tested the generated output with https://editor.swagger.io/)

Looking forward to this update :)

Thanks again!

Simon

**Comment by WoH** [comment]
Thank you for your contribution! :clap:

**Pull request merged**
