### PR TITLE
test: cannot read properties of undefined (reading 'typeParameters')

### PR DESCRIPTION
**Pull request by simllll**
with the tsoa 6.0.0-rc.3 the following definition
 `headers: Map<string, unknown>`
 results in:
```
Generate routes error.
 Error: Cannot read properties of undefined (reading 'typeParameters') 
 in 'ParameterController.brokenUndefinedMap'
    at new GenerateMetadataError (/home/simon/Dev/others/tsoa/src/metadataGeneration/exceptions.ts:6:5)
    at /home/simon/Dev/others/tsoa/src/metadataGeneration/methodGenerator.ts:70:15
    at Array.map (<anonymous>)
    at MethodGenerator.buildParameters (/home/simon/Dev/others/tsoa/src/metadataGeneration/methodGenerator.ts:64:45)
    at MethodGenerator.Generate (/home/simon/Dev/others/tsoa/src/metadataGeneration/methodGenerator.ts:53:24)
    at /home/simon/Dev/others/tsoa/src/metadataGeneration/controllerGenerator.ts:49:35
    at Array.map (<anonymous>)
    at ControllerGenerator.buildMethods (/home/simon/Dev/others/tsoa/src/metadataGeneration/controllerGenerator.ts:49:8)
    at ControllerGenerator.Generate (/home/simon/Dev/others/tsoa/src/metadataGeneration/controllerGenerator.ts:38:21)
    at /home/simon/Dev/others/tsoa/src/metadataGeneration/metadataGenerator.ts:88:35
error Command failed with exit code 1.
```

works with rc.2 though.

this line breaks it:
https://github.com/lukeautry/tsoa/blob/6c3d4e15cea3fb2185fd805a2bac25bd1414b3fd/packages/cli/src/metadataGeneration/typeResolver.ts#L1040

it seems that `const declaration = this.getModelTypeDeclaration(targetEntity);` returns undefined, question is why though.

leaving this here for now, as I cannot see what change has introduced this bug right now, but will look at it again. If you have any ideas/feedback , let me know :)

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [ ] This PR is associated with an existing issue?

**Closing issues**

**Test plan**

### CODE REVIEW

**Comment by WoH** [comment]
Is there any chance you changed the TS version alongside the tsoa bump?

**Comment by simllll** [comment]
We used for sure typescript 5.1.x before and are now on 5.1.6, but could be a patch release that got updated during this, I will look into it.l and report back.

**Comment by WoH** [comment]
Well, almost, except if that exact test would've been failing before rc.2, which is not unlikely.
Unfortunately, TS is not very kind to upstream users w/r/t breaking changes in the compiler API.

**Comment by simllll** [comment]
Yeah, but as we had this type definition in our code base before, and it popped up with the update, I'm pretty confident that it must be related to rc.3.

Will check it though to be safe, I give another update next week.

**Pull request closed without merging**
