### PR TITLE
feat: support using custom multer instance in RegisterRoutes

### LINKED ISSUE #1483: Add ability to inject our custom multer instance to tsoa
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Ability to add my own custom multer instance to the tsoa instance as follow:

```ts
const multerInstance: Multer.Multer = multer({ ...your config here});

// it could be something like
RegisterRoutes(app, {
    multer: multerInstance
});
```
since above method seems out of scope for the `RegisterRoutes` function, we could do something like

```ts
RegisterMulter(multerInstance);
RegisterRoutes(app);
```
 the above code would provide tsoa with the the`multerInstance` which it would use as it's multer instance instead of initializing it's own multer instance.

## Current Behavior

Although we can customize the multerOpts using the tsoa.json, it seems to be incomplete as it is incapable of inserting storage engine to the multerOpts, rightfully so as it is a json file. This has caused some issue when i wanted to use [multer-s3](https://www.npmjs.com/package/multer-s3) as the storage engine for multer and also maintain the single truth in controller idea. 

- > Using the `@UploadedFile` decorator will use the tsoa's multer instance, which cannot use multer-s3 is not a valid option.

- > Inserting my own multer middleware on top of the decorator will cause the request to fail as two multer instances(my multer-s3 multer instance and tsoa's multer instance) try to read file from the same request. 
- > Only using the middleware will cause the swagger file to not have information about the file(although this can be mitigated by using [this](https://tsoa-community.github.io/docs/file-upload.html#custom-multer-upload) guide, I think this is a tedious and bandaid solution which doesn't follow the tsoa mantra of having single truth controller)  

## Possible Solution

See Expected Behaviour

P.S. I am new here, if I broke any rules, i apologize in advance.

### PR DESCRIPTION
**Pull request by midoelhawy**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [x] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

closes #1483
### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by WoH** [comment]
LGTM, but can we add a test in one of the setups maybe?

**Comment by midoelhawy** [comment]
Hi @WoH,

Makes sense. I've now added the automatic tests to avoid bad configuration errors:

```
cross-env NODE_ENV=tsoa_test mocha "./integration/express-server-custom-multer.spec.ts"

  Express Server With custom multer
    file upload With custom multer instance
      ✔ can post a file (71ms)
      ✔ can post a file without name
      ✔ cannot post a file with wrong attribute name
      ✔ can post multiple files with other form fields
      ✔ can post single file to multi file field
      ✔ can post multiple files with different field
      ✔ can post multiple files with different array fields
      ✔ can post mixed form data content with file and not providing optional file
      ✔ can post mixed form data content with file and provides optional file

  9 passing (239ms)
```

Thanks!

**Comment by midoelhawy** [comment]
Hi @WoH,

There were some ESLint errors outside my edited files, but they were resolved by merging master into my branch. Everything works now.

Can you run the tests again, please?

**Comment by midoelhawy** [comment]
Hi @WoH,

These errors are related to @typescript-eslint rules. They appeared only after cleaning the yarn.lock, so I think they're related to some new @typescript-eslint patch.



```Log
/home/work/tsoa/tsoa/packages/cli/src/metadataGeneration/transformer/referenceTransformer.ts
17:40 error This assertion is unnecessary since it does not change the type of the expression @typescript-eslint/no-unnecessary-type-assertion
21:35 error This assertion is unnecessary since it does not change the type of the expression @typescript-eslint/no-unnecessary-type-assertion

/home/work/tsoa/tsoa/packages/cli/src/metadataGeneration/typeResolver.ts
144:43 error This assertion is unnecessary since it does not change the type of the expression @typescript-eslint/no-unnecessary-type-assertion

/home/work/tsoa/tsoa/packages/cli/src/swagger/specGenerator2.ts
441:54 error This assertion is unnecessary since it does not change the type of the expression @typescript-eslint/no-unnecessary-type-assertion

/home/work/tsoa/tsoa/packages/cli/src/swagger/specGenerator3.ts
105:28 error This assertion is unnecessary since it does not change the type of the expression @typescript-eslint/no-unnecessary-type-assertion
```


I fixed them by ignoring the errors in some cases and by fixing the types when possible.

Can you run the Build action again, please?

**Comment by WoH** [comment]
LGTM, thanks for your contribution, and, tbh, your patience

**Pull request merged**
