### PR TITLE
feat(cli): add parameter deprecation capability

### LINKED ISSUE #1345: `@Deprecated()` decorator not working with `@FormField()`
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request (? I let you decide)
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Usage of `@Deprecated()` on `@FormField()` should set `deprecated: true` correctly, like in the doc [here](https://tsoa-community.github.io/docs/decorators.html#parameters-openapi-3-only).

Example:

```ts
@Get("v2")
public async findV2(
  @FormField() text: string,
  @Deprecated() @FormField() dontUse?: string
): Promise<any> {

}
```

## Current Behavior

No deprecation is generated in `openapi.json`.

## Context (Environment)

Version of the library: 4.1.3
Version of NodeJS: v16.17.1

- Confirm you were using yarn not npm: [ ]

### PR DESCRIPTION
**Pull request by Jule-**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [x] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

closes #1345 

**Test plan**

Help needed! Happy to add unit tests to check deprecated generation, but I need to be headed toward where to put them.

### CODE REVIEW

**Comment by Jule-** [comment]
As mentioned, there is no unit test yet and I am happy to produce one with some help.

**Comment by Jule-** [comment]
FTR parameter deprecation has been introduced in v3 of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#parameter-object

**Comment by WoH** [comment]
You'd want to test this by creating another controller method similar to this one:
https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/controllers/postController.ts#L76

Then, in the spec details for OpenAPI 3, add assertions that the deprecated parameter is correctly set.
Take a look at the other tests here: https://github.com/lukeautry/tsoa/blob/master/tests/unit/swagger/schemaDetails3.spec.ts#L425

**Comment by Jule-** [comment]
Here you go. Hope I did it the way you wanted. Happy to amend commits if you have some review comments.
Cheers!

**Comment by WoH** [comment]
LGTM, thanks!

**Pull request merged**
