### PR TITLE
put type field for nullable

### PR DESCRIPTION
**Pull request by gwprice115**
### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [ ] This PR is associated with an existing issue?

**Closing issues**
closes https://github.com/lukeautry/tsoa/issues/1550
Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

**Test plan**

### CODE REVIEW

**Comment by gwprice115** [comment]
would love some confirmation that this will be accepted before i write the test

**Comment by gwprice115** [comment]
i think this is correct but i've hacked around it locally so won't push for it

**Comment by WoH** [comment]
I think the result is not correct here, esp/ since we should only put a type on the target of the ref nd only it it's nullable, right?

**Comment by gwprice115** [comment]
I think you're right it's only needed if it's nullable, but putting it on the target of the ref won't solve the issues i linked in the Issue

**Pull request closed without merging**
