### PR TITLE
Fix: Don't include 'content' in 204 responses

### LINKED ISSUE #702: "A 204 response must not include a message-body"
Generated swagger.json breaks validation, which breaks SDK generation.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Generated swagger.json should validate properly.

## Current Behavior

Currently, Tsoa generates:
```
"204": {
	"content": {
		"application/json": {}
	},
	"description": ""
}
```
for `Promise<void>` returns.  This causes validation to fail (I'm using https://github.com/IBM/openapi-validator), which, in turn, breaks client generation.

```yaml

```

```ts
```

## Possible Solution

Simply omitting the
```"application/json": {}```
makes it work again.

I believe, though, I haven't tested it yet, that moving the `if (res.schema && !isVoidType(res.schema))` statement [here](https://github.com/lukeautry/tsoa/blob/05e6bcc33bde4ea32aa53ea830895594eb608cb0/src/swagger/specGenerator3.ts#L283) up to [here](https://github.com/lukeautry/tsoa/blob/05e6bcc33bde4ea32aa53ea830895594eb608cb0/src/swagger/specGenerator3.ts#L277) might fix the problem.

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: tsoa@3.0.8
Version of NodeJS: v12.11.1

- Confirm you were using yarn not npm: [x]

## Detailed Description

image

image

### PR DESCRIPTION
**Pull request by aktary**
Conforms to https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5

Closes #702 

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

**Closing issues**

Put `closes #XXXX` (where XXXX is the issue number) in your comment to auto-close the issue that your PR fixes.

### If this is a new feature submission:

- [ ] Has the issue had a maintainer respond to the issue and clarify that the feature is something that aligns with the [goals](https://github.com/lukeautry/tsoa#goal) and [philosophy](https://github.com/lukeautry/tsoa#philosophy) of the project?

**Potential Problems With The Approach**

Only addresses v3 generator.

**Test plan**

### CODE REVIEW

**Comment by WoH** [comment]
2 questions:
1) Do you know if OpenAPI 2 is fine?
2) Could you add a small test around this?

I'd suggest something like this below tests/unit/swagger/definitionsGeneration/metadata.spec.ts:229

```ts
const oas3 = new SpecGenerator3(metadata, getDefaultExtendedOptions()).GetSpec();
expect(oas3.paths['/GetTest/void'].get.responses[204].to.not.haveOwnProperty('content')
```

**Comment by aktary** [comment]
> 2 questions:
> 
> 1. Do you know if OpenAPI 2 is fine?

The same validator didn't complain about the v2 version I just generated, so yes, I guess it's ok.

> 2. Could you add a small test around this?

Sure... thanks for pointing me in the right direction. Updated PR coming...

**Comment by aktary** [comment]
Sorry for the merge commit... Test done and passing.  Also fixed a logic error in the originally proposed solution.

**Comment by WoH** [comment]
I moved the test since you added a new controller method in the getController and removed the console.log statement. Hope you don't mind. LGTM

**Pull request merged**
