### PR TITLE
fix: refType with {}, [] and { foo: number }

### PR DESCRIPTION
**Pull request by Eywek**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
* [x] Have you written unit tests?
* [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
* [ ] This PR is associated with an existing issue?

### CODE REVIEW

**Comment by WoH** [comment]
Would be nice to add a test here, but the approach lgtm.

**Comment by Eywek** [comment]
I've removed the line
```
        .replace(/([a-z]+)\[([a-z]+)\]/gi, '$1~$2~') // Partial_SerializedDatasourceWithVersion[format]_ -> Partial_SerializedDatasourceWithVersion~format~_
```
and I'll add it to the Indexed type PR.

I've added a test

**Comment by Eywek** [comment]
We're good with this one @WoH?

**Comment by WoH** [comment]
One Question: What happens if there are multiple props?
`Generic<{foo: number; bar: boolean}>` ?

**Comment by Eywek** [comment]
Good question, I've updated the test
`Generic<{foo: number; bar: boolean}>` -> `Generic__foo-string--bar-boolean__`

**Comment by Eywek** [comment]
Maybe we can merge?

**Pull request merged**
