### PR TITLE
Handled undefined Identifier

### LINKED ISSUE #112: Generation fails when using decorators without braces
Took me five hours to get the generator running.
I always got this error in cli:

```
Generate swagger error.
   TypeError: Cannot read property 'text' of undefined

  - controllerGenerator.js:47
    [TradingBot]/[tsoa]/dist/metadataGeneration/controllerGenerator.js:47:33

  - Array.filter

  - controllerGenerator.js:45 ControllerGenerator.getControllerDecoratorValue
    [TradingBot]/[tsoa]/dist/metadataGeneration/controllerGenerator.js:45:14

  - controllerGenerator.js:37 ControllerGenerator.getControllerRouteValue
    [TradingBot]/[tsoa]/dist/metadataGeneration/controllerGenerator.js:37:21

  - controllerGenerator.js:9 new ControllerGenerator
    [TradingBot]/[tsoa]/dist/metadataGeneration/controllerGenerator.js:9:31

  - metadataGenerator.js:45
    [TradingBot]/[tsoa]/dist/metadataGeneration/metadataGenerator.js:45:55

  - Array.map

  - metadataGenerator.js:45 MetadataGenerator.buildControllers
    [TradingBot]/[tsoa]/dist/metadataGeneration/metadataGenerator.js:45:14

  - metadataGenerator.js:22 MetadataGenerator.Generate
    [TradingBot]/[tsoa]/dist/metadataGeneration/metadataGenerator.js:22:32

  - cli.js:109 Object.handler
    [TradingBot]/[tsoa]/dist/cli.js:109:91

  - command.js:170 Object.self.runCommand
    [TradingBot]/[tsoa]/[yargs]/lib/command.js:170:22

  - yargs.js:920 parseArgs
    [TradingBot]/[tsoa]/[yargs]/yargs.js:920:28

  - yargs.js:860 Object.get [as argv]
    [TradingBot]/[tsoa]/[yargs]/yargs.js:860:16

  - cli.js:160 Object.<anonymous>
    [TradingBot]/[tsoa]/dist/cli.js:160:5

  - module.js:570 Module._compile
    module.js:570:32

  - module.js:579 Object.Module._extensions..js
    module.js:579:10
```

The cause of this problem seems fairly simple:
```
import autobind from './autobind';

@autobind
export class Disposable implements IDisposable {
    // ...
}
```

Typescripts allows you to leave the braces behind the decorator Name.
Unfortinutely this causes the TypeError above.

My solution was to add "()" behind every decorator and it worked.

Possible fix for this error in file "controllerGenerator.js" in line 47:
```
        var matchedAttributes = node.decorators
            .map(function (d) { return d.expression; })
            .filter(function (expression) {
            var subExpression = expression.expression;
            return (subExpression && subExpression.text) === decoratorName; // <-- fix
        });
```

Greetings, Martin

### PR DESCRIPTION
**Pull request by MatthiasKunnen**
Fixes #112

### CODE REVIEW

**Comment by endor** [comment]
Is it possible to add a test for this? Is it enough to leave out the `()` from one of the fixtures?

**Comment by MatthiasKunnen** [comment]
Yes, it should be enough to leave out the `() ` but the decorator needs to support this. Non of the tsoa decorators support decorators without parentheses. So we need to create one for testing purposes only. I got a bit lost in the tests searching for a place to add this.

**Comment by MatthiasKunnen** [comment]
I looked a bit deeper into why this error occurs and how decorators are made up.

There are multiple ways to declare decorators. One uses the form `@expression`, where expression must evaluate to a function that will be called at runtime with information about the decorated declaration. I'll refer to these as simple decorators. Another way is described as _decorator factories_. 

> A Decorator Factory is simply a function that returns the expression that will be called by the decorator at runtime. <http://www.typescriptlang.org/docs/handbook/decorators.html#decorator-factories>

The object returned by `node.decorators` differs in structure for simple decorators and decorator factories. 

**Decorator factory object**
```
NodeObject {
  pos: 1186,
  end: 1210,
  flags: 0,
  transformFlags: 536875011,
  parent: NodeObject {...}
  kind: 149,
  expression: 
   NodeObject {
     pos: 1190,
     end: 1210,
     flags: 8192,
     transformFlags: 536870912,
     parent: [Circular],
     kind: 185,
     expression: 
      IdentifierObject {
        pos: 1190,
        end: 1193,
        flags: 8192,
        parent: [Circular],
        escapedText: 'Get',
        flowNode: [Object],
        transformFlags: 536870912 },
     arguments: [ [TokenObject], pos: 1194, end: 1209, transformFlags: 536870912 ] } }
```

**simple decorator object**
```
NodeObject {
  pos: 312,
  end: 338,
  flags: 0,
  transformFlags: 536875011,
  parent: NodeObject {...},
  kind: 149,
  expression: 
   IdentifierObject {
     pos: 319,
     end: 338,
     flags: 8192,
     parent: [Circular],
     escapedText: 'NonFactoryDecorator',
     flowNode: { flags: 2 },
     transformFlags: 536870912 } }
```

The getDecorators function incorrectly assumes that the `NodeObject` always has `object.expression.expression`. I'll update this PR to deal with both structures accordingly.

**Comment by endor** [comment]
Just out of curiosity, why use `while` instead of `if`?

**Comment by MatthiasKunnen** [comment]
To go down further if `expression.expression.expression` exists. I think it might exist if there would be another function wrapped in there. I don't know for sure. It's a precaution.

**Pull request merged**
