### PR TITLE
Tuple support (WIP)

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
### It's not worth reviewing this yet, please don't waste your time

This is a **very** work-in-progress implementation of tuple support I did a couple of months ago. I still have to go through it and look if I can do things better with improved knowledge of the codebase. 
I'm posting this now to avoid people starting on implementing this too (double work) and to remind myself that I still need to properly implement this.

Right now it basically only contains the basic type resolution needed to make TSOA run with models that contain tuples, which is what I needed for the project I was working on. It was made in a big rush (tight deadline) so there are probably some stupidities in here, once I feel like it's ready (or if someone just really wants to pick at my code) I'll be happy to hear about them ;)

I have no idea how the Swagger/OpenAPI format works, so if someone could tune in on how we can represent tuples there I'd love to hear about it 😄

The issue for this (#242) was closed for some reason without this being implemented, maybe it should be opened up again?

### CODE REVIEW

**Comment by dgreene1** [comment]
> I have no idea how the Swagger/OpenAPI format works, so if someone could tune in on how we can represent tuples there I'd love to hear about it

I have no interest in working on this myself since I would never ask a user of my api to send a tuple. I would ask them to send an object that has two properties. However, I’m happy to answer how a tuple would look in Swagger:

In Swagger 2:
```yaml
type: array
items:
  type: integer
minItems: 2
maxItems: 2
```
Notice that it only supports a tuple if the same type. So like [string, string]. Anything else and we would have to warn that the tuple of mixed type is unsupported and the user would have to change to SpecVersion 3 to get what they want. To be super clear, I will not approve a PR that doesn’t have that warning. We’ve set that precedence with the union/intersection PR.

OpenAPI 3.0 supports mixed array types so it could be capable of rendering a tuple of of mixed types like this:

```yaml
type: array
items:
  oneOf:
    - $ref: '#/components/schemas/Cat'
    - $ref: '#/components/schemas/Dog'
minItems: 2
maxItems: 2
```

**Comment by WoH** [comment]
> OpenAPI 3.0 supports mixed array types so it could be capable of rendering a tuple of of mixed types like this

A quick thing to note: Even OAPI3 has no way to enforce the order of types as far as I know, but I'd be happy to be wrong here.

**Comment by HoldYourWaffle** [comment]
> I have no interest in working on this myself since I would never ask a user of my api to send a tuple. I would ask them to send an object that has two properties.

I'm using TSOA as more like an RPC solution, for some functions it makes sense to have a data format that contains tuples.

> Anything else and we would have to warn that the tuple of mixed type is unsupported and the user would have to change to SpecVersion 3 to get what they want. To be super clear, I will not approve a PR that doesn’t have that warning. We’ve set that precedence with the union/intersection PR.

Makes sense, will do.

> A quick thing to note: Even OAPI3 has no way to enforce the order of types as far as I know, but I'd be happy to be wrong here.

I wouldn't be surprised if this was the case.

Even if Swagger/OpenAPI doesn't really support (mixed) tuples, I still think the type resolution should be added. Without it it's impossible to use TSOA if one of your models (indirectly) contains a tuple type, which doesn't make a lot of sense if you aren't using Swagger/OpenAPI (or only homogeneous tuples).

**Comment by WoH** [comment]
> Even if Swagger/OpenAPI doesn't really support (mixed) tuples, I still think the type resolution should be added. Without it it's impossible to use TSOA if one of your models (indirectly) contains a tuple type, which doesn't make a lot of sense if you aren't using Swagger/OpenAPI (or only homogeneous tuples).

I would agree with that. Just means the validation might throw error messages that can't be read from the OAPI spec itself.

**Comment by HoldYourWaffle** [comment]
> we should not provide runtime validation that can not be communicated via Swagger/OpenAPI.

Personally I'd say that runtime validation shouldn't be TSOA's business at all because I see it as just an auto-generation library/framework, but this is of course entirely up to you. I don't have to use it, so I'm not bothered by it either.

> converts heterogenous tuples if Spec version 3 has been set

What do you mean by convert?

> warns if heterogenous tuples have been used if spec version 2 has been set

Wouldn't an error be better suited since it's not possible to represent them in any form?

> throws in the presence of any mixed-type tuples with an error stating that “mixed-type tuples are not supported in either Swagger Spec 2 or in OpenAPI 3.0”

Now I'm confused. What's the difference between mixed-type and heterogenous tuples?

<br>

> Seeing as this PR doesn’t have any implementation yet or any tests, I’m closing this PR for housekeeping purposes. If you are interested in writing a PR that meets the above acceptance criteria, then we would welcome the PR.

I don't see any reason why this PR should be closed for "housekeeping". It's clearly marked as WIP both in the title and by being marked as "draft" in the github UI.
It's true that I haven't added tests or swagger generation yet, but it's not like it's an "empty PR". The type resolution is already there, which I would say is about half of the work already done.
It's not the finished product yet, but it's a starting point for others that might be interested that they can comment/build on.

Of course if you really want me to I can create the exact same PR from the exact same branch in a couple of days (or weeks depending on how long the 'discussion phase' takes) with a couple of extra commits added, but I think that only "clutters" the project's history more if that's what you're concerned about. But if you really want me to, of course I'll do that, you're the maintainer after all.

**Comment by WoH** [comment]
> When people are considering using a library, they look at the count of open issues/PRs as a marker of whether or not the library is being maintained or not. The only reason that I stepped up to become the maintainer of tsoa is so that I can help make tsoa look more professional so that it can reach a wider audience. PRs like this that are not ready to be merged only increase the count and therefore hurt tsoa's goal of being used by more people.

I'd strongly urge you to reconsider the reasoning here, this statement really made my skin crawl.
Closing PRs for nothing but what you perceive to be "professional appearance" is shortsighted and counterproductive in my opinion.
Draft PRs can be used as a helpful tool to discuss code and approaches, these should be subject to criticism, not involvement with the community through suggested code.

I'll just leave just a few impressions:
https://github.com/rails/rails/pulls
https://github.com/kubernetes/kubernetes/pulls
https://github.com/nodejs/node/pulls

If you're interested in a thriving community, I think promoting discussion is a lot better than suppressing it.

**Comment by HoldYourWaffle** [comment]
I fully agree with @WoH on this. Seeing another PR of mine closed, without a clear reason why it should be *closed* instead of *requesting changes* really made me rethink if it's even worth contributing.
Also I consider open PR's/issues a sign of activity rather than "deadness", but the most important judgement factors for me are things like recent activity in the form of commits.

>This is the red flag. There should be an intent to discuss, which I'm not is the case here

There was, I just worded it very wrong. I mostly said that to protect myself from "this is not finished", "where are the tests" or "what about swagger" comments, which are of course very logical and true with the current state of this PR, but I already knew about those things.
The main reasons why I opened this PR in such an early stage was to ask how to represent tuples in Swagger and to lessen the chance that somebody else starts implementing this (hopefully preventing double work).

**Comment by WoH** [comment]
> Yes, I can see how having code samples might make it easier to have a conversation. That being said, we can’t have people working on features that tsoa might not even be considered. That’s what the issues are for. That’s where the conversations should happen. I really would prefer that we don’t open PRs if there are multiple questions.

Please note that I do not disagree with the decision, I would just prefer to see a more consistent line of argumentation on why this should be closed. It's somewhat unfortunate that you are in a position where it would've been helpful for the Contributor Guidelines to state that the project would not accept functionality that can't be specified using OAPI. However, that would've been a perfectly fine argument to make.

> this is my first time stepping up as a maintainer for a large open-source project, so I appreciate your feedback on how I’ve been doing.

Although this won't always come through in the heat of the moment, I deeply respect your work and your willingness to discuss these topics in your free time without an iron fist. We may disagree on some issues, but I value the work you do for tsoa immensely and I am very appreciative of that and should probably emphasize that a lot more.

> That being said, I’d appreciate if you please assume best intentions. I am doing my best to foster a community but also to put some groundwork in so that PRs don’t languish and get dusty. 

I do and I see why you think this is the best thing going forward, but I, for my personal interest, would not like to see pandering towards people making decisions based on stars and open PRs to affect contributors. I, as a biased person, felt like this specific argument should not have been made in the way it was done and felt like I should bring it up. It was not my intention to question your intentions at any point, but, what I perceive to be a suboptimal way to get there.

**Comment by HoldYourWaffle** [comment]
> Your draft PRs have been very helpful. But there was a pretty large difference between your PRs and this current one we’re discussing.

Ouch... 😉 I understand that it might've been a *little* early to submit this PR, but I hope the reasons I listed earlier explained my reasoning.

> I will review any PR or issue that's created.

And I really appreciate that, especially the speed at which you're doing it...

> That being said, we can’t have people working on features that tsoa might not even be considered.

This is of course true, but in this case I didn't see any reason why tuples shouldn't be supported. Even with my limited knowledge of Swagger/OpenAPI I knew that there was a min/max-items "thing" for arrays so that at least homogeneous tuples could be implemented. I also posted [this comment](https://github.com/lukeautry/tsoa/issues/242#issuecomment-502392061) saying that I had started working on this, and since there weren't any "negative responses" so to speak I didn't see a reason to stop.

> That’s what the issues are for. That’s where the conversations should happen. I really would prefer that we don’t open PRs if there are multiple questions.

I have to say that this is a little unusual for me. It's not wrong, if that's how you want to handle maintaining this project that's entirely your call. But as said many times before, such things probably need to be mentioned in a contributor guide.

> I have done that right @HoldYourWaffle, right? Like haven’t I provided a lot of feedback (here, here, and here) on how to represent the swagger specs?

You have, and without that help it would never be possible for me to finish this PR 😄. I mentioned it in order to clarify that my intent for this PR was discussion (which I worded badly as pointed out by WoH).

> I’ll reopen this PR because I don’t want anyone to accuse me of silencing ideas.

I'm not trying to accuse you of anything like that, I just felt that closing this PR for 'housekeeping purposes' was a little "overcautious" so to speak. You said that more discussion was needed, and I 100% agree.

> However, my concern is that this PR will stay open like some of the other PRs We closed because they were 2+ years old and the original authors did not demonstrate interest in fixing the requested changes. Perhaps my fear is unfounded.

This is of course a real problem, but there are automated solutions for that. I don't think closing PR's that are still actively being worked on is the solution for this.

<br>

> @WoH / @HoldYourWaffle, this is my first time stepping up as a maintainer for a large open source project, so I appreciate your feedback on how I’ve been doing. That being said, I’d appreciate if you please assume best intentions.

(I completely agree with @WoH so I'm not going to repeat everything he said)

I think you're doing very well considering it's your first time! The only feedback I'd give is to be a *little* more flexible with certain things, but we already discussed that in detail 😉

> The time it’s taken to provide feedback on PRs has already taken more time then I have, and I’m concerned that I may no longer be able to provide the level of support that you are expecting of a maintainer. As far as I know, I am the last remaining maintainer besides Luke who has asked me to take up ownership.

You really shouldn't spend more time on this than you can handle. Your response have been exceptionally quick, and while very convenient I don't think it's necessary for a maintainer to always be "on alert". There's no harm in taking your time to respond, some waiting can do wonders on both sides of a discussion. In other words: please take your free time. You should only spend as much time on this as you want, even if that means some things will have to wait a little longer.

That being said I think it'd be good to appoint a "second maintainer". Perhaps not with full merge privileges, but I think github recently added a "triage" role that can only close/open/label/... issues/PR. I've seen some bigger projects that have a couple of these people as "first line of defence" to check incoming issues/PR's before bothering the main maintainer to cast their judgement on it. Given my track record I think you'd be more comfortable with @WoH taking on such a role (if he wants to), but I'd be happy to do it as well if you feel comfortable with that.

> Do you have any recommendations on how we can perhaps automate PRs that have remained unchanged for too long?

Stalebot should do the trick. An automated test runner like travis could also help with catching stupid test errors like #448.

**Comment by HoldYourWaffle** [comment]
Is it just me or are all my comments way too long? Is it the quotes or is my writing style just very long? I don't get it.

Please say so if it bothers you, I'll try to make my comments shorter.

**Comment by HoldYourWaffle** [comment]
Oh right I forgot I never finished this.

I simply don't have the time to work on this right now, but I'll see if I can squeeze it in somewhere next week.

**Comment by Eywek** [comment]
any news on this?

**Comment by WoH** [comment]
We can't type tuples (in terms of OpenAPI), which is the major issue here.

**Pull request closed without merging**
